version: '3.9'

services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 5000:80
    container_name: web_app

  redis:
    image: "redis:6.0.9"
    container_name: redis_app